name: Publish to Chrome Web Store

on:
  push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Build zip file
        run: zip -r release.zip . -x ".*" "*/.*"

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@2.1.1
        with:
          action: 'publish' 
          client_id: ${{ secrets.CLIENT }}
          client_secret: ${{ secrets.SECRET }}
          refresh_token: ${{ secrets.TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: 'release.zip'
